### ISSUE TITLE
I think it may be broken

### ISSUE THREAD

**Issue by DeanAndMason1314** [RusJJ/GorillaFriends#9]
I went into a public lobby and saw the text but on the leader borad it just said "player name" 5 times and didnt show anyones name

**Comment by RusJJ** [comment]
Probably the newest update broke it, thanks for the report. Sadly i cannot really check what's wrong

**Comment by dmkdev1** [comment]
But can you fix? its okay if you cant just wondering

**Comment by RusJJ** [comment]
> But can you fix? its okay if you cant just wondering

Has been updated. Please check if there is any problems... https://github.com/RusJJ/GorillaFriends/releases/tag/pre-1.2.1-v3

**Comment by ghost** [comment]
![20240317033052_1](https://github.com/RusJJ/GorillaFriends/assets/134834878/81519451-616e-49aa-b4ce-28a64e81e9c0)
This is what it does when you add players

**Comment by dmkdev1** [comment]
Um so im trying to install it and it keeps just dissapering when i try to put it in the plugins

**Comment by dmkdev1** [comment]
also when i unzipped it there was no .dll

**Comment by dmkdev1** [comment]
again Norton is saying its a theat and is deleting it

**Comment by dmkdev1** [comment]
i fixed the issue

**Comment by dmkdev1** [comment]
i tried the mod it works

**Comment by RusJJ** [comment]
Probably completely working version, cant really check rn (but i did earlier):

https://github.com/RusJJ/GorillaFriends/releases/tag/pre-1.2.1-v4

**Comment by dmkdev1** [comment]
its working!
Good mod!

**Comment by RusJJ** [comment]
Thanks for letting me know. Need to fix one more glitch and it will be ready to use again!

**Comment by ghost** [comment]
> Thanks for letting me know. Need to fix one more glitch and it will be ready to use again!

Okay
